/* Resource File Indices for MEMFIL31 */

#define MAINWIND 0   /* Form/Dialog */
#define BOX      0   /* BOX in tree MAINWIND */
#define UPARR    1   /* BOXCHAR in tree MAINWIND */
#define DISPLAY  2   /* BOX in tree MAINWIND */
#define ADDRSTR  3   /* STRING in tree MAINWIND */
#define TOPSTR   4   /* TEXT in tree MAINWIND */
#define BOX1     7   /* BOX in tree MAINWIND */
#define BOX2     8   /* BOX in tree MAINWIND */
#define SLIDER   9   /* BOX in tree MAINWIND */
#define SLIDBOX  10  /* BOX in tree MAINWIND */
#define DNARR    11  /* BOXCHAR in tree MAINWIND */
#define MEMORY   13  /* BUTTON in tree MAINWIND */
#define GETMAP   15  /* BUTTON in tree MAINWIND */
#define SEARCH   16  /* BUTTON in tree MAINWIND */
#define GETCOPY  17  /* BUTTON in tree MAINWIND */
#define ADDRDEC  20  /* FBOXTEXT in tree MAINWIND */
#define ADDRHEX  21  /* FBOXTEXT in tree MAINWIND */
#define DECIMAL  24  /* BUTTON in tree MAINWIND */
#define HEX      25  /* BUTTON in tree MAINWIND */
#define FILE     27  /* BUTTON in tree MAINWIND */
#define FILENAME 28  /* FTEXT in tree MAINWIND */
#define SELECTOR 29  /* BUTTON in tree MAINWIND */
#define SECTOR   31  /* BUTTON in tree MAINWIND */
#define SECMINUS 33  /* BOXCHAR in tree MAINWIND */
#define SECNUM   34  /* FBOXTEXT in tree MAINWIND */
#define SECPLUS  35  /* BOXCHAR in tree MAINWIND */
#define SWAP     37  /* BUTTON in tree MAINWIND */
#define DRIVE    38  /* BUTTON in tree MAINWIND */
#define SECINFO  39  /* TEXT in tree MAINWIND */

#define EDITOR   1   /* Form/Dialog */

#define DRIVES   2   /* Form/Dialog */
#define DRIVEA   1   /* BOXCHAR in tree DRIVES */
#define DRVCANC  17  /* BUTTON in tree DRIVES */

#define SEARCHF  3   /* Form/Dialog */
#define SRCHASC  3   /* FBOXTEXT in tree SEARCHF */
#define SRCHHEX  4   /* FBOXTEXT in tree SEARCHF */
#define ALERTON  7   /* BOX in tree SEARCHF */
#define SRCHXIT  8   /* BUTTON in tree SEARCHF */

#define MAP      4   /* Form/Dialog */

#define COPY     5   /* Form/Dialog */
#define COPSM    3   /* BUTTON in tree COPY */
#define COPSMS   4   /* FBOXTEXT in tree COPY */
#define COPSME   5   /* FBOXTEXT in tree COPY */
#define COPSF    6   /* BUTTON in tree COPY */
#define COPSFS   7   /* FBOXTEXT in tree COPY */
#define COPSFE   8   /* FBOXTEXT in tree COPY */
#define COPSS    9   /* BUTTON in tree COPY */
#define COPSSDR  10  /* FBOXTEXT in tree COPY */
#define COPSSS   11  /* FBOXTEXT in tree COPY */
#define COPSSE   12  /* FBOXTEXT in tree COPY */
#define COPGETFN 13  /* BUTTON in tree COPY */
#define COPFRAW  16  /* BUTTON in tree COPY */
#define COPFLYES 20  /* BUTTON in tree COPY */
#define COPFLCH  22  /* FTEXT in tree COPY */
#define COPDM    25  /* BUTTON in tree COPY */
#define COPDMS   26  /* FBOXTEXT in tree COPY */
#define COPDF    27  /* BUTTON in tree COPY */
#define COPDFS   28  /* FBOXTEXT in tree COPY */
#define COPDS    29  /* BUTTON in tree COPY */
#define COPDSD   30  /* FBOXTEXT in tree COPY */
#define COPDSS   31  /* FBOXTEXT in tree COPY */
#define COPDP    32  /* BUTTON in tree COPY */
#define COPYIT   33  /* BUTTON in tree COPY */

#define FNAMES   6   /* Form/Dialog */
#define FNSRC    1   /* FTEXT in tree FNAMES */
#define FNSSEL   2   /* BUTTON in tree FNAMES */
#define FNSMAIN  3   /* BUTTON in tree FNAMES */
#define FNDEST   4   /* FTEXT in tree FNAMES */
#define FNDSEL   5   /* BUTTON in tree FNAMES */
#define FNDMAIN  6   /* BUTTON in tree FNAMES */
#define FNDONE   7   /* BUTTON in tree FNAMES */

#define MED1     7   /* Form/Dialog */

#define MED2     8   /* Form/Dialog */

#define MED3     9   /* Form/Dialog */

#define MED4     10  /* Form/Dialog */

#define MED5     11  /* Form/Dialog */

#define MED6     12  /* Form/Dialog */

#define MED7     13  /* Form/Dialog */
